### ISSUE TITLE
`p_mask` redefined without being used

### ISSUE THREAD

**Issue by shabie** [suicao/coleridge-gpt#1]
Hello. Thanks a lot for sharing the repo and congrats on the brilliant win!

So, I was going through the code and saw something that I couldn't quite follow. Why was the `p_mask` redefined on line 98 as a zero matrix without being used?

https://github.com/suicao/coleridge-gpt/blob/f49f998a1aef5b8c8be71b73b94e90e0dbe58ee1/code/train.py#L93-L100

**Comment by suicao** [comment]
That should be a bug. the `p_mask` should be `1.0` for all padding tokens so that the softmax output for those positions are always almost zero. If it's not manually set like you pointed out then the model will discover it by itself anyway, but the training will be a bit less stable.
